# Report templates configuration
# This file contains templates for market analysis reports

# Main report template
report_template: |
  # AI市场洞察报告

  ## 主题：{topic}
  ## 类目：{category_name}

  ---

# Conclusion template
conclusion_template: |
  ## 结论与建议

  根据以上分析，我们为{category_name}设计团队提供以下立意方向和策略建议：

  - **设计灵感**：基于用户关注的热门元素和情感诉求，融入设计中。
  - **市场定位**：针对核心受众，制定符合其需求的产品策略。
  - **差异化竞争**：突出产品独特性，避免同质化，提升竞争优势。
  - **联动策略**：探索与「{topic}」相关的跨界合作机会，扩大品牌影响力。
  - **形象设计**：生成一条「{topic}」Midjourney形象设计的提示词，概括关键设计要素和创意亮点。

# Section templates for different analysis aspects
section_templates:
  market_analysis: |
    ## {level}市场分析

    {response}

    ---

  trend_analysis: |
    ## {level}趋势分析

    {response}

    ---

  consumer_insight: |
    ## {level}消费者洞察

    {response}

    ---

  competitive_analysis: |
    ## {level}竞品分析

    {response}

    ---

  channel_strategy: |
    ## {level}渠道策略

    {response}

    ---
