# Report templates configuration
# This file contains templates for market analysis reports

# YAML frontmatter template
frontmatter_template: |
  ---
  title: "AI市场洞察报告"
  subtitle: "{topic} - {category_name}分析"
  author: "自动生成"
  date: "{current_date}"
  lang: "zh-CN"
  ---

# Main report template
report_template: |
  ---
  title: AI市场洞察报告
  subtitle: "{topic} {category_name}分析"
  author: AI Market Insights
  date: \today
  documentclass: article
  CJKmainfont: Noto Sans CJK SC
  geometry: margin=1in
  header-includes:
    - \usepackage{xeCJK}
    - \usepackage{indentfirst}
    - \setlength{\parindent}{2em}
  ---

  # AI市场洞察报告

  ## 基本信息
  ### 主题：{topic}
  ### 类目：{category_name}

  ---
  

# Conclusion template
conclusion_template: |
  ## 结论与建议

  ### 策略建议
  根据以上分析，我们为{category_name}设计团队提供以下立意方向和策略建议：

  - **设计灵感**：基于用户关注的热门元素和情感诉求，融入设计中。
  - **市场定位**：针对核心受众，制定符合其需求的产品策略。
  - **差异化竞争**：突出产品独特性，避免同质化，提升竞争优势。
  - **联动策略**：探索与「{topic}」相关的跨界合作机会，扩大品牌影响力。
  - **形象设计**：生成一条「{topic}」Midjourney形象设计的提示词，概括关键设计要素和创意亮点。

  ---

  注意事项：
  - 所有列表项应使用减号（-）作为标记
  - 列表项应保持一致的缩进（2个空格）
  - 子列表项应在父列表项下额外缩进2个空格

# Section templates for specialized analysis aspects
section_templates:
  hot_trends: |
    ## {level}热点趋势分析

    {response}

    ---

  emotional_analysis: |
    ## {level}情感分析

    {response}

    ---

  trend_prediction: |
    ## {level}趋势预测

    {response}

    ---

  audience_analysis: |
    ## {level}受众画像分析

    {response}

    ---

  user_segmentation: |
    ## {level}用户群体细分

    {response}

    ---

  market_data: |
    ## {level}市场数据分析

    {response}

    ---

  differentiation: |
    ## {level}差异化策略

    {response}

    ---

  design_prompt: |
    ## {level}设计提示

    {response}

    ---
