# Report templates configuration
# This file contains templates for market analysis reports

# Main report template
report_template: |
  # AI市场洞察报告

  ## 主题：{topic}
  ## 类目：{category_name}

  ---

# Conclusion template
conclusion_template: |
  ## 结论与建议

  根据以上分析，我们为{category_name}设计团队提供以下立意方向和策略建议：

  - **设计灵感**：基于用户关注的热门元素和情感诉求，融入设计中。
  - **市场定位**：针对核心受众，制定符合其需求的产品策略。
  - **差异化竞争**：突出产品独特性，避免同质化，提升竞争优势。
  - **联动策略**：探索与「{topic}」相关的跨界合作机会，扩大品牌影响力。
  - **形象设计**：生成一条「{topic}」Midjourney形象设计的提示词，概括关键设计要素和创意亮点。

# Section templates for specialized analysis aspects
section_templates:
  hot_trends: |
    ## {level}热点趋势分析

    {response}

    ---

  emotional_analysis: |
    ## {level}情感分析

    {response}

    ---

  trend_prediction: |
    ## {level}趋势预测

    {response}

    ---

  audience_analysis: |
    ## {level}受众画像分析

    {response}

    ---

  user_segmentation: |
    ## {level}用户群体细分

    {response}

    ---

  market_data: |
    ## {level}市场数据分析

    {response}

    ---

  differentiation: |
    ## {level}差异化策略

    {response}

    ---

  design_prompt: |
    ## {level}设计提示

    {response}

    ---
